package pos1_2ahif.ex_4_tamagochi.engine.api;

import pos1_2ahif.ex_4_tamagochi.engine.impl.Frame;

/**
 * Interface for creating Ascii-Art Frames
 */
public interface FrameFactory {
    /**
     * Creates a frame based on 3 Strings:
     *
     * Use this variant when you want to display pictures.
     *
     * @param syms this will be the actual symbols displayed
     * @param fg this will set the foreground Colors of the symbols
     * @param bg this will set the background Colors of the symbols
     * @return a frame generated by the strings
     */
    Frame fromStrings(String syms, String fg, String bg);

    /**
     * Creates a frame based on Text Segments:
     *
     * Use this variant when you want to display text
     *
     * @param segments list of segments to render, a segment contains a text and a fore ground and background color pattern
     * @return a frame generated by the segments
     */
    Frame fromSegments(FrameSegment... segments);
}
